version: "3"
services:
  postgres:
    image: postgres:latest
    network_mode: bridge
    container_name: ${DB_CONTAINER_NAME}
    expose:
    - 5432
    ports:
      - ${PORT_FORWARD}:5432
    volumes:
      - ./file_table.sql:/docker-entrypoint-initdb.d/file_table.sql
      - ./train_table.sql:/docker-entrypoint-initdb.d/train_table.sql
      - ./airflow_ddl.sql:/docker-entrypoint-initdb.d/airflow_ddl.sql
      # /mnt/postgres/data:/var/lib/postgresql/data
    # env_file:
    #   - ./db.env
    environment:
         - TZ=Asia/Seoul
         - POSTGRES_USER=${DB_USER}
         - POSTGRES_PASSWORD=${DB_PW}
         - POSTGRES_DB=${DB_NAME}
         - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    restart: always

  mlserver:
      image: ${DOCKER_IMAGE}:${DOCKER_VERSION}
      restart: always
      container_name: ${ML_CONTAINER_NAME}
      ports:
          - ${AIZT_PORT}:${DOCKER_PORT}
          - 7070:8080
      environment:
          - XEDM_HOME=${XEDM_HOME}
          - XEDM_WORKING_STG=${XEDM_WORKING_STG}
          - MODEL_PATH=${MODEL_PATH}



# COMPOSE FILE 우선순위
# 1. Compose file
# 2. Shell environment variables
# 3. Environment file
# 4. Dockerfile
# 5. Variable is not defined